import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {chromium} from 'playwright';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
const root=new URL('../..',import.meta.url).pathname;const scratch=await mkdtemp(join(tmpdir(),'pc-sync-browser-'));
execFileSync('esbuild',['tests/notifications/fixtures/app.tsx','--bundle',`--outfile=${join(scratch,'app.js')}`,'--alias:@/frontend/utils/supabase/client=./tests/notifications/fixtures/supabase.ts'],{cwd:root});
const bundle=await readFile(join(scratch,'app.js'),'utf8');const css=(await postcss([tailwind()]).process(await readFile(join(root,'app/globals.css'),'utf8'),{from:join(root,'app/globals.css')})).css;
for(const width of [1440,390])test(`Omnichannel campaign sync, channels and specific internal users persist at ${width}px`,{timeout:60000},async()=>{
 let settings={notification_matrix:{tickets:{ticket_created:{channels:{email:true,whatsapp:false,push:false},roles:['staff']}}},whatsapp_templates:{ticket_created:{campaign_name:'existing_ticket',params:['user_name']},unlisted_event:{campaign_name:'keep_me',params:[]}},email_templates:{tickets:{html:'Existing tickets template'}}};
 const server=createServer(async(req,res)=>{res.setHeader('content-type','application/json');if(req.url.startsWith('/api/admin/organizations/')){if(req.method==='PATCH'){let body='';for await(const part of req)body+=part;settings={...settings,...JSON.parse(body)};}res.end(JSON.stringify(settings));}else if(req.url.startsWith('/api/petty-cash/notification-deliveries'))res.end(JSON.stringify({deliveries:[]}));else if(req.url.startsWith('/api/'))res.end(JSON.stringify({users:[],logs:[]}));else{res.setHeader('content-type','text/html');res.end(`<style>${css}</style><div id="root"></div><script>${bundle.replace(/<\/script/gi,'<\\/script')}</script>`);}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto(url);await page.getByRole('navigation',{name:'Notification modules'}).getByRole('button',{name:'Petty Cash',exact:true}).click();const event=page.locator('[data-notification-event="petty_cash_submitted"]');await event.getByRole('button',{name:'WhatsApp',exact:true}).waitFor();assert.equal(await event.getByRole('button',{name:'WhatsApp',exact:true}).getAttribute('aria-pressed'),'false');assert.equal(await event.getByRole('button',{name:'Push',exact:true}).getAttribute('aria-pressed'),'false');assert.equal(await event.getByRole('button',{name:'Voice',exact:true}).count(),0);
  await event.getByRole('button',{name:'Push',exact:true}).click();await event.getByRole('button',{name:'WhatsApp',exact:true}).click();await event.getByRole('button',{name:'+ Add user...',exact:true}).click();await event.getByPlaceholder('Search by name, email, or role...').fill('Allocator');await event.getByRole('button',{name:/Fixture Allocator/}).click();await event.getByText('Fixture Allocator',{exact:true}).waitFor();assert.equal(await event.getByRole('checkbox',{name:'Notify Assigned Allocator',exact:true}).isChecked(),false);
  await event.getByRole('button',{name:'+ Add user...',exact:true}).click();await event.getByPlaceholder('Search by name, email, or role...').fill('Vendor');assert.equal(await event.getByRole('button',{name:/Fixture Vendor/}).count(),0);await page.mouse.click(1,1);
  await Promise.all([page.waitForResponse(r=>r.request().method()==='PATCH'),page.getByRole('button',{name:'Save Settings',exact:true}).click()]);assert.equal(settings.notification_matrix.petty_cash.petty_cash_submitted.enabled,true);assert.deepEqual(settings.notification_matrix.petty_cash.petty_cash_submitted.user_ids,['00000000-0000-0000-0000-000000000012']);assert.equal(settings.notification_matrix.petty_cash.petty_cash_submitted.channels.whatsapp,true);assert.equal(settings.notification_matrix.petty_cash.petty_cash_submitted.channels.push,true);assert.equal(settings.notification_matrix.petty_cash.petty_cash_submitted.notify_assignee,false);
  await page.getByRole('button',{name:'Templates',exact:true}).click();await page.getByRole('heading',{name:'Petty Cash WhatsApp templates',exact:true}).waitFor();assert.equal(await page.locator('[data-template-draft]').count(),7);await page.getByRole('button',{name:'Import seven live Petty Cash campaign names',exact:true}).click();assert.equal(await page.getByLabel('AiSensy campaign for Request submitted',{exact:true}).inputValue(),'pc_action_required_v1');await page.getByLabel('AiSensy campaign for Request submitted',{exact:true}).fill('my_live_action_campaign');await Promise.all([page.waitForResponse(r=>r.request().method()==='PATCH'),page.getByRole('button',{name:'Save Campaign Templates',exact:true}).click()]);assert.equal(settings.whatsapp_templates.petty_cash_submitted.campaign_name,'my_live_action_campaign');assert.equal(settings.whatsapp_templates.petty_cash_submitted.confirmed_live,true);assert.equal(settings.whatsapp_templates.ticket_created.campaign_name,'existing_ticket');assert.equal(settings.whatsapp_templates.unlisted_event.campaign_name,'keep_me');assert.equal(Object.keys(settings.whatsapp_templates).filter(key=>key.startsWith('petty_cash_')).length,15);
  await page.getByLabel('Petty Cash email event',{exact:true}).selectOption('petty_cash_paid');await page.getByRole('button',{name:'Use built-in email template',exact:true}).click();await Promise.all([page.waitForResponse(r=>r.request().method()==='PATCH'),page.getByRole('button',{name:'Save Petty Cash email template',exact:true}).click()]);assert.match(settings.email_templates.petty_cash_paid.html,/Bills and receipts are optional/);assert.equal(settings.email_templates.tickets.html,'Existing tickets template');
  await page.screenshot({path:join(scratch,`settings-${width}.png`),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page overflow');await page.reload();await page.getByRole('navigation',{name:'Notification modules'}).getByRole('button',{name:'Petty Cash',exact:true}).click();await page.locator('[data-notification-event="petty_cash_submitted"]').getByText('Fixture Allocator',{exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('Settings screenshots:',scratch);
 }catch(error){console.log('Browser failure:',await page.locator('body').innerText());throw error;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
});
