'use client';
import { useEffect, useMemo, useState } from 'react';
import { inr, PC_STATUS_META } from '@/frontend/lib/pettyCash/roles';
import { pcFetch } from './workflowTypes';
interface Row { id: string; request_no: string; requester_id: string; requester_name: string; property_id: string; property_name: string; status: string; paid: number; spent: number; balance: number; unresolved_proofs: number; requested: number; allocated: number; approved: number; created_at: string; assigned_allocator_id?: string; assigned_approver_id?: string }
export default function ConsolidatedOverview({ org, onOpen }: { org: string; onOpen: (id: string) => void }) {
    const [rows, setRows] = useState<Row[]>([]); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [property, setProperty] = useState(''); const [status, setStatus] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
    useEffect(() => { let active = true; pcFetch<{ rows: Row[] }>(`/api/petty-cash/tracker?org_id=${org}`).then(data => { if (active) setRows(data.rows); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [org]);
    const filtered = useMemo(() => rows.filter(r => (!property || property === r.property_id) && (!status || status === r.status) && (!from || r.created_at.slice(0, 10) >= from) && (!to || r.created_at.slice(0, 10) <= to) && `${r.requester_name} ${r.request_no}`.toLowerCase().includes(search.toLowerCase())), [rows, property, status, from, to, search]);
    return <div className="space-y-4"><h2 className="text-lg font-bold">Consolidated petty cash</h2>{error && <p role="alert">{error}</p>}
        <div className="flex flex-wrap gap-3"><input className="pc-input max-w-xs" aria-label="Filter requester" placeholder="Requester or request number" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Filter property" className="pc-input max-w-xs" value={property} onChange={e => setProperty(e.target.value)}><option value="">All properties</option>{[...new Map(rows.map(r => [r.property_id, r.property_name])).entries()].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select aria-label="Filter status" className="pc-input max-w-xs" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{Object.entries(PC_STATUS_META).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select><label>From<input type="date" className="pc-input" value={from} onChange={e => setFrom(e.target.value)} /></label><label>To<input type="date" className="pc-input" value={to} onChange={e => setTo(e.target.value)} /></label></div>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{(['requested', 'allocated', 'approved', 'paid', 'spent', 'balance'] as const).map(key => <div key={key} className="rounded-xl border border-border p-4"><p className="capitalize">{key}</p><strong>{inr(filtered.reduce((sum, r) => sum + Number(r[key] || 0), 0))}</strong></div>)}</div>
        <p>{filtered.length} requests · {filtered.reduce((sum, r) => sum + Number(r.unresolved_proofs), 0)} unresolved proofs</p>
        <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Request', 'Requester', 'Property', 'Status', 'Paid', 'Spent', 'Remaining', 'Proof issues'].map(h => <th key={h} className="text-left p-2">{h}</th>)}</tr></thead><tbody>{filtered.map(r => <tr key={r.id} className="border-t border-border"><td className="p-2"><button className="underline" onClick={() => onOpen(r.id)}>{r.request_no}</button></td><td>{r.requester_name}</td><td>{r.property_name}</td><td>{PC_STATUS_META[r.status]?.label}</td><td>{inr(r.paid)}</td><td>{inr(r.spent)}</td><td>{inr(r.balance)}</td><td>{r.unresolved_proofs}</td></tr>)}</tbody></table></div>
    </div>;
}
