'use client';
import { useEffect, useMemo, useState } from 'react';
import { inr, PC_STATUS_META } from '@/frontend/lib/pettyCash/roles';
import { pcFetch } from './workflowTypes';
interface Row { id: string; request_no: string; requester_id: string; requester_name: string; property_id: string; property_name: string; status: string; request_type: string; paid: number; spent: number; balance: number; unresolved_proofs: number; requested: number; allocated: number; approved: number; created_at: string; assigned_allocator_id?: string; assigned_approver_id?: string; assigned_allocator_name?: string; assigned_approver_name?: string }
export default function ConsolidatedOverview({ org, onOpen }: { org: string; onOpen: (id: string) => void }) {
    const [rows, setRows] = useState<Row[]>([]); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [property, setProperty] = useState(''); const [status, setStatus] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [actor, setActor] = useState(''); const [requester, setRequester] = useState(''); const [page, setPage] = useState(1);
    useEffect(() => { let active = true; pcFetch<{ rows: Row[] }>(`/api/petty-cash/tracker?org_id=${org}`).then(data => { if (active) setRows(data.rows); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [org]);
    const filtered = useMemo(() => rows.filter(r => (!property || property === r.property_id) && (!requester || requester === r.requester_id) && (!status || status === r.status) && (!actor || actor === r.assigned_allocator_id || actor === r.assigned_approver_id) && (!from || r.created_at.slice(0, 10) >= from) && (!to || r.created_at.slice(0, 10) <= to) && `${r.requester_name} ${r.request_no}`.toLowerCase().includes(search.toLowerCase())), [rows, property, requester, status, actor, from, to, search]);
    const wallets = useMemo(() => { const result = new Map<string, { name: string; paid: number; spent: number; balance: number; proofs: number }>(); for (const r of filtered) { if (r.request_type === 'reimbursement') continue; const wallet = result.get(r.requester_id) || { name: r.requester_name, paid: 0, spent: 0, balance: 0, proofs: 0 }; wallet.paid += Math.round(Number(r.paid) * 100); wallet.spent += Math.round(Number(r.spent) * 100); wallet.balance += Math.round(Number(r.balance) * 100); wallet.proofs += Number(r.unresolved_proofs); result.set(r.requester_id, wallet); } return [...result.entries()]; }, [filtered]);
    const actors = [...new Map(rows.flatMap(r => [[r.assigned_allocator_id, r.assigned_allocator_name], [r.assigned_approver_id, r.assigned_approver_name]] as [string | undefined, string | undefined][]).filter(([id]) => id)).entries()];
    const pages = Math.max(1, Math.ceil(filtered.length / 50)); const currentPage = Math.min(page, pages);
    return <div className="space-y-4"><h2 className="text-lg font-bold">Consolidated petty cash</h2>{error && <p role="alert">{error}</p>}
        <div className="flex flex-wrap gap-3"><input className="pc-input max-w-xs" aria-label="Filter requester" placeholder="Requester or request number" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Filter property" className="pc-input max-w-xs" value={property} onChange={e => setProperty(e.target.value)}><option value="">All properties</option>{[...new Map(rows.map(r => [r.property_id, r.property_name])).entries()].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select aria-label="Filter status" className="pc-input max-w-xs" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{Object.entries(PC_STATUS_META).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select><label>From<input type="date" className="pc-input" value={from} onChange={e => setFrom(e.target.value)} /></label><label>To<input type="date" className="pc-input" value={to} onChange={e => setTo(e.target.value)} /></label></div>
        <label className="block max-w-xs">Assigned actor<select aria-label="Assigned actor" className="pc-input" value={actor} onChange={e => { setActor(e.target.value); setPage(1); }}><option value="">All assigned actors</option>{actors.map(([id, name]) => <option key={id} value={id}>{name || id}</option>)}</select></label>
        <label className="block max-w-xs">Requester<select aria-label="Requester" className="pc-input" value={requester} onChange={e => { setRequester(e.target.value); setPage(1); }}><option value="">All requesters</option>{[...new Map(rows.map(row => [row.requester_id, row.requester_name])).entries()].map(([id, name]) => <option key={id} value={id}>{name} ({id.slice(-8)})</option>)}</select></label>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{(['requested', 'allocated', 'approved', 'paid', 'spent', 'balance'] as const).map(key => <div key={key} className="rounded-xl border border-border p-4"><p className="capitalize">{key}</p><strong>{inr(filtered.reduce((sum, r) => sum + Math.round(Number(r[key] || 0) * 100), 0) / 100)}</strong></div>)}</div>
        <p>{filtered.length} requests · {filtered.reduce((sum, r) => sum + Number(r.unresolved_proofs), 0)} unresolved proofs</p>
        <p>{filtered.filter(r => ['submitted', 'pending_approval', 'approved'].includes(r.status)).length} awaiting allocation, approval or payment · {filtered.filter(r => ['paid', 'settlement_submitted'].includes(r.status)).length} awaiting reconciliation</p>
        <details><summary className="cursor-pointer font-bold">Wallets & spends by requester ({wallets.length})</summary><p>Totals reflect the selected filters. Confirmed cash returns reduce remaining cash.</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Requester', 'Received', 'Spent', 'Remaining', 'Proof issues'].map(h => <th className="text-left p-2" key={h}>{h}</th>)}</tr></thead><tbody>{wallets.map(([id, w]) => <tr key={id} className="border-t border-border"><td className="p-2"><button className="underline" onClick={() => { setRequester(id); setPage(1); }}>{w.name}</button></td><td>{inr(w.paid / 100)}</td><td>{inr(w.spent / 100)}</td><td>{inr(w.balance / 100)}</td><td>{w.proofs}</td></tr>)}</tbody></table></div></details>
        <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Request', 'Requester', 'Property', 'Status', 'Paid', 'Spent', 'Remaining', 'Proof issues'].map(h => <th key={h} className="text-left p-2">{h}</th>)}</tr></thead><tbody>{filtered.slice((currentPage - 1) * 50, currentPage * 50).map(r => <tr key={r.id} className="border-t border-border"><td className="p-2"><button className="underline" onClick={() => onOpen(r.id)}>{r.request_no}</button></td><td>{r.requester_name}</td><td>{r.property_name}</td><td>{PC_STATUS_META[r.status]?.label}</td><td>{inr(r.paid)}</td><td>{inr(r.spent)}</td><td>{inr(r.balance)}</td><td>{r.unresolved_proofs}</td></tr>)}</tbody></table></div>
        <div className="flex justify-end gap-3"><button disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Previous</button><p>Page {currentPage} of {pages}</p><button disabled={currentPage === pages} onClick={() => setPage(currentPage + 1)}>Next</button></div>
    </div>;
}
