'use client';
import { useEffect, useState } from 'react';
import { pcFetch, pcJson, type Context } from './workflowTypes';
interface Candidate { id: string; full_name: string; email: string; roles?: string[]; property_association?: string }
interface Assignment { property_id: string; kind: string; user_id: string; is_primary: boolean; user?: { full_name?: string; email?: string } }
export default function PropertyRoutingSettings({ context, onSaved }: { context: Context; onSaved: () => void }) {
    const [property, setProperty] = useState(context.configuration_properties[0]?.id || '');
    const [users, setUsers] = useState<Candidate[]>([]);
    const [allocator, setAllocator] = useState(''); const [approver, setApprover] = useState('');
    const [allocatorBackups, setAllocatorBackups] = useState<string[]>([]); const [approverBackups, setApproverBackups] = useState<string[]>([]);
    const [configuredNames, setConfiguredNames] = useState<Record<string, string>>({});
    const [search, setSearch] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
    useEffect(() => {
        if (!property) return; let active = true; setUsers([]); setAllocator(''); setApprover(''); setAllocatorBackups([]); setApproverBackups([]); setMessage('');
        Promise.all([pcFetch<{ users: Candidate[] }>(`/api/petty-cash/candidates?org_id=${context.organization_id}&property_id=${property}`), pcFetch<{ assignments: Assignment[] }>(`/api/petty-cash/assignments?org_id=${context.organization_id}`)]).then(([candidates, config]) => { if (!active) return; setUsers(candidates.users); const rows = config.assignments.filter(r => r.property_id === property); setConfiguredNames(Object.fromEntries(rows.map(r => [r.user_id, r.user?.full_name || r.user?.email || 'Previously configured user']))); setAllocator(rows.find(r => r.kind === 'allocator' && r.is_primary)?.user_id || ''); setApprover(rows.find(r => r.kind === 'approver' && r.is_primary)?.user_id || ''); setAllocatorBackups(rows.filter(r => r.kind === 'allocator' && !r.is_primary).map(r => r.user_id)); setApproverBackups(rows.filter(r => r.kind === 'approver' && !r.is_primary).map(r => r.user_id)); }).catch(e => { if (active) setMessage(e.message); });
        return () => { active = false; };
    }, [property, context.organization_id]);
    const matches = users.filter(u => `${u.full_name} ${u.email}`.toLowerCase().includes(search.toLowerCase()) || u.id === allocator || u.id === approver || allocatorBackups.includes(u.id) || approverBackups.includes(u.id));
    const label = (u: Candidate) => `${u.full_name || u.email} (${u.email})${u.roles?.length ? ` — ${u.roles.join(', ')} · ${u.property_association}` : ''}`;
    return <form className="space-y-4 max-w-2xl" onSubmit={async event => { event.preventDefault(); setBusy(true); setMessage(''); try { await pcFetch('/api/petty-cash/assignments', pcJson({ organization_id: context.organization_id, property_id: property, allocator_id: allocator, approver_id: approver, allocator_backups: allocatorBackups.filter(id => id !== allocator), approver_backups: approverBackups.filter(id => id !== approver) }, 'PUT')); setMessage('Routing saved. New requests will use these users; reassign pending requests explicitly.'); onSaved(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Save failed'); } finally { setBusy(false); } }}>
        <h2 className="text-lg font-bold">Property Routing</h2><p>Configure the users who allocate and approve petty cash. Requesters cannot choose them.</p>
        <label className="block">Property<select aria-label="Property" className="pc-input" value={property} onChange={e => setProperty(e.target.value)}>{context.configuration_properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
        <input className="pc-input" aria-label="Find routing user" placeholder="Search users by name or email" value={search} onChange={e => setSearch(e.target.value)} />
        <label className="block">Allocator<select className="pc-input" required aria-label="Allocator" value={allocator} onChange={e => setAllocator(e.target.value)}><option value="">Select allocator</option>{matches.map(u => <option key={u.id} value={u.id}>{label(u)}</option>)}</select></label>
        <label className="block">Approver<select className="pc-input" required aria-label="Approver" value={approver} onChange={e => setApprover(e.target.value)}><option value="">Select approver</option>{matches.filter(u => u.id !== allocator).map(u => <option key={u.id} value={u.id}>{label(u)}</option>)}</select></label>
        <p className="text-sm">Backups act only after a super admin assigns a pending request to them. Select up to 25 per stage.</p>
        {(['allocator', 'approver'] as const).map(kind => { const selected = kind === 'allocator' ? allocatorBackups : approverBackups; const setSelected = kind === 'allocator' ? setAllocatorBackups : setApproverBackups; return selected.filter(id => !users.some(user => user.id === id)).map(id => <div key={`${kind}_${id}`} className="rounded-xl border border-amber-400 p-3"><p>{configuredNames[id]} is no longer eligible as an {kind} backup for this property. Remove this selection before saving.</p><button className="underline" type="button" disabled={busy} onClick={() => setSelected(previous => previous.filter(userId => userId !== id))}>Remove unavailable {kind} backup: {configuredNames[id]}</button></div>); })}
        {(['allocator', 'approver'] as const).map(kind => <fieldset className="rounded-xl border border-border p-3" key={kind}><legend>{kind === 'allocator' ? 'Allocator backups' : 'Approver backups'}</legend><div className="max-h-48 overflow-y-auto space-y-2">{matches.filter(u => u.id !== (kind === 'allocator' ? allocator : approver)).map(u => { const selected = kind === 'allocator' ? allocatorBackups : approverBackups; const setSelected = kind === 'allocator' ? setAllocatorBackups : setApproverBackups; return <label key={u.id} className="flex gap-2 items-start"><input type="checkbox" checked={selected.includes(u.id)} disabled={busy || (!selected.includes(u.id) && selected.length >= 25)} onChange={e => setSelected(previous => e.target.checked ? [...previous, u.id] : previous.filter(id => id !== u.id))} />{label(u)}</label>; })}</div></fieldset>)}
        <button className="pc-button" disabled={busy || !allocator || !approver || allocator === approver}>{busy ? 'Saving…' : 'Save routing'}</button>{message && <p role="status">{message}</p>}
    </form>;
}
