import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { chromium } from 'playwright';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
import sharp from 'sharp';
import { id, setup, call } from './database.mjs';
const root=new URL('../..',import.meta.url).pathname;
// Run via npm exec --package=esbuild -- node --test tests/petty-cash/browser.test.mjs.
const scratch=await mkdtemp(join(tmpdir(),'petty-cash-browser-'));
execFileSync('esbuild',['tests/petty-cash/fixtures/app.tsx','--bundle',`--outfile=${join(scratch,'app.js')}`,'--alias:next/navigation=./tests/petty-cash/fixtures/navigation.ts','--alias:next/link=./tests/petty-cash/fixtures/link.tsx','--alias:@/frontend/context/AuthContext=./tests/petty-cash/fixtures/auth.ts','--alias:@/frontend/utils/supabase/client=./tests/petty-cash/fixtures/supabase.ts'],{cwd:root});
const bundle=await readFile(join(scratch,'app.js'),'utf8');
const css=(await postcss([tailwind()]).process(await readFile(join(root,'app/globals.css'),'utf8'),{from:join(root,'app/globals.css')})).css;
const png=await sharp({create:{width:100,height:80,channels:3,background:'white'}}).png().toBuffer();
async function fixture(db){
 const files=new Map();
 const reqRow=async(r)=>{const user=(await db.query('select id,full_name,email from users where id=$1',[r.requester_id])).rows[0];const property=(await db.query('select id,name from properties where id=$1',[r.property_id])).rows[0];const actors=(await db.query('select id,full_name,email from users where id in ($1,$2)',[r.assigned_allocator_id,r.assigned_approver_id])).rows;return {...r,requester:user,property,assigned_allocator:actors.find(a=>a.id===r.assigned_allocator_id),assigned_approver:actors.find(a=>a.id===r.assigned_approver_id)};};
 const server=createServer(async(req,res)=>{try{
  const url=new URL(req.url,'http://fixture');const actor=id(Number(req.headers['x-fixture-actor']||url.searchParams.get('actor')||11));
  if(!url.pathname.startsWith('/api/')){res.setHeader('content-type','text/html');res.end(`<style>${css}</style><div id="root"></div><script>${bundle.replace(/<\/script/gi,'<\\/script')}</script>`);return;}
  const parts=[];for await(const part of req)parts.push(part);const bytes=Buffer.concat(parts);let body={};if((req.headers['content-type']||'').includes('application/json'))body=JSON.parse(bytes.toString());
  let data;
  if(url.pathname.endsWith('/context')){
   const wallet=await call(db,'pc_wallet',[actor,id(1)]);const superAdmin=await call(db,'pc_super',[actor,id(1)]);const pm=(await db.query('select p.id,p.name from properties p join property_memberships m on p.id=m.property_id where m.user_id=$1 and m.is_active',[actor])).rows;
   const assignments=(await db.query('select a.*,jsonb_build_object(\'id\',u.id,\'full_name\',u.full_name,\'email\',u.email) "user" from petty_cash_property_assignments a join users u on u.id=a.user_id where is_active and is_primary')).rows;
   const assigned=(await db.query('select * from petty_cash_property_assignments where user_id=$1',[actor])).rows;
   const finance=Number(req.headers['x-fixture-actor'])===14;
   data={organization_id:id(1),user_id:actor,properties:pm.length?pm:superAdmin?(await db.query('select id,name from properties')).rows:[],configuration_properties:superAdmin?(await db.query('select id,name from properties')).rows:[],wallet,counts:await call(db,'pc_pending_counts',[actor,id(1)]),routes:assignments,caps:{isAdmin:superAdmin,canManageRouting:superAdmin,canAllocate:assigned.some(a=>a.kind==='allocator'),canApprove:assigned.some(a=>a.kind==='approver'),canDisburse:finance}};
  }else if(url.pathname.endsWith('/assignments')){
   if(req.method==='PUT')data={routing:await call(db,'pc_set_routing',[actor,body.property_id,body.allocator_id,body.approver_id,body.allocator_backups||[],body.approver_backups||[]])};else{if(!await call(db,'pc_super',[actor,id(1)]))throw Error('Forbidden');data={assignments:(await db.query(`select a.*,jsonb_build_object('full_name',u.full_name,'email',u.email) "user" from petty_cash_property_assignments a join users u on u.id=a.user_id where a.is_active`)).rows};}
  }else if(url.pathname.endsWith('/candidates')){if(!await call(db,'pc_super',[actor,id(1)]))throw Error('Forbidden');data={users:(await db.query('select id,full_name,email from users where pc_internal(id,$1,$2)',[id(1),url.searchParams.get('property_id')])).rows};
  }else if(url.pathname.endsWith('/upload')){
   const request=new Request('http://fixture',{method:'POST',headers:req.headers,body:bytes});const form=await request.formData();const file=form.get('file');const uid=crypto.randomUUID();const path=`${id(1)}/${actor}/${uid}.png`;files.set(path,Buffer.from(await file.arrayBuffer()));await db.query('insert into petty_cash_uploads(id,organization_id,uploaded_by,storage_path,file_name,file_type) values ($1,$2,$3,$4,$5,$6)',[uid,id(1),actor,path,file.name,file.type]);data={upload_id:uid,file_name:file.name,file_type:file.type};
  }else if(url.pathname.endsWith('/bulk')){
   const results=[];for(const item of body.items){try{results.push({id:item.id,ok:true,request:await call(db,'pc_action',[actor,item.id,body.action,item])});}catch(e){results.push({id:item.id,ok:false,error:e.message});}}data={results};
  }else if(url.pathname.endsWith('/tracker'))data=await call(db,'pc_report',[actor,id(1)]);
  else if(url.pathname==='/api/petty-cash/expenses')data={expenses:(await db.query(`select e.*,jsonb_build_object('id',r.id,'request_no',r.request_no) request,jsonb_build_object('id',p.id,'name',p.name) property,coalesce((select jsonb_agg(jsonb_build_object('id',d.id,'file_name',d.file_name,'file_type',d.file_type,'superseded_by',d.superseded_by)) from petty_cash_documents d where d.expense_id=e.id),'[]'::jsonb) documents from pc_my_expenses($1,$2)e join petty_cash_requests r on r.id=e.request_id join properties p on p.id=e.property_id order by e.expense_date desc,e.created_at desc,e.id desc`,[actor,id(1)])).rows,total_pages:1};
  else if(/\/documents\/[^/]+\/download$/.test(url.pathname)){
   const doc=(await db.query('select * from petty_cash_documents where id=$1',[url.pathname.split('/').at(-2)])).rows[0];if(!doc||!await call(db,'pc_can_read',[actor,doc.request_id]))throw Error('Forbidden');res.setHeader('content-type',doc.file_type);res.end(files.get(doc.storage_path));return;
  }else if(/\/expenses\/[^/]+$/.test(url.pathname))data={expense:body.action==='correct'?await call(db,'pc_correct_expense',[actor,url.pathname.split('/').at(-1),body]):await call(db,'pc_review_expense',[actor,url.pathname.split('/').at(-1),body.review_status,body.remark||''])};
  else if(/\/[^/]+\/expenses$/.test(url.pathname))data={expense:await call(db,'pc_expense',[actor,url.pathname.split('/').at(-2),body])};
  else if(url.pathname==='/api/petty-cash'){
   if(req.method==='POST')data={request:await call(db,'pc_create_request',[actor,id(1),body])};else{
    let rows=(await db.query('select * from pc_requests($1,$2) order by created_at desc',[actor,id(1)])).rows;const tab=url.searchParams.get('tab');
    if(tab==='allocations')rows=rows.filter(r=>r.assigned_allocator_id===actor&&r.status==='submitted');else if(tab==='approvals')rows=rows.filter(r=>r.assigned_approver_id===actor&&r.status==='pending_approval');else if(tab==='disbursements')rows=rows.filter(r=>r.status==='approved');else if(tab==='reconciliation')rows=rows.filter(r=>['paid','settlement_submitted'].includes(r.status));else if(tab==='assigned')rows=rows.filter(r=>r.assigned_allocator_id===actor||r.assigned_approver_id===actor);else if(tab!=='all')rows=rows.filter(r=>r.requester_id===actor);data={requests:await Promise.all(rows.map(reqRow)),pagination:{total_pages:1}};
   }
  }else{
   const rid=url.pathname.split('/').at(-1);
   if(req.method==='PATCH')data={request:await call(db,'pc_action',[actor,rid,body.action,body])};else{
    if(!await call(db,'pc_can_read',[actor,rid]))throw Error('Forbidden');const r=(await db.query('select * from petty_cash_requests where id=$1',[rid])).rows[0];const balance=await call(db,'pc_balance',[id(1),r.requester_id,rid]);const totals=(await db.query("select coalesce(sum(amount)filter(where kind='credit'),0)received,coalesce(sum(amount)filter(where kind='debit'),0)spent,coalesce(sum(amount)filter(where kind='return'),0)returned from petty_cash_wallet_entries where request_id=$1",[rid])).rows[0];data={request:await reqRow(r),balance,wallet:{received:Number(totals.received),spent:Number(totals.spent),returned:Number(totals.returned),balance:Number(balance)},documents:(await db.query('select * from petty_cash_documents where request_id=$1',[rid])).rows,expenses:(await db.query('select * from petty_cash_expenses where request_id=$1 order by expense_date desc,created_at desc,id desc',[rid])).rows,activity:(await db.query('select * from petty_cash_activity where request_id=$1',[rid])).rows};
   }
  }
  res.setHeader('content-type','application/json');res.end(JSON.stringify(data));
 }catch(e){res.statusCode=/Forbidden/i.test(e.message)?403:409;res.setHeader('content-type','application/json');res.end(JSON.stringify({error:e.message}));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));return {server,url:`http://127.0.0.1:${server.address().port}`};
}
async function chooseRouting(page, label, name) {
 await page.getByRole('combobox',{name:label,exact:true}).click();
 await page.getByRole('textbox',{name:`Search ${label.toLowerCase()}`,exact:true}).fill(name);
 await page.getByRole('option',{name,exact:false}).click();
}
test('searchable primary routing saves selected people and removes previous backups', {timeout:90000}, async()=>{
 const db=await setup();await db.query('update users set email=$1 where id=$2',['cash.person@example.test',id(16)]);await call(db,'pc_set_routing',[id(10),id(3),id(12),id(13),[id(16)],[]]);
 const {server,url}=await fixture(db);const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage();
 try {
  await page.goto(`${url}/?actor=10`);await page.getByRole('button',{name:'Property Routing',exact:true}).click();
  await page.getByRole('combobox',{name:'Allocator',exact:true}).click();
  assert.equal(await page.getByRole('textbox',{name:'Search allocator',exact:true}).count(),1,'Allocator dropdown must have its own search');
  await page.getByRole('textbox',{name:'Search allocator',exact:true}).fill('no such person');assert.equal(await page.getByRole('option').count(),0);
  await page.getByRole('textbox',{name:'Search allocator',exact:true}).fill('cash.person');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
  await chooseRouting(page,'Approver','Fixture 13');await page.getByRole('combobox',{name:'Property',exact:true}).click();await page.getByRole('textbox',{name:'Search property'}).fill('Property B');await page.keyboard.press('Escape');assert.equal(await page.getByRole('textbox',{name:'Search property'}).count(),0);assert.equal(await page.getByRole('combobox',{name:'Property',exact:true}).evaluate(el=>document.activeElement===el),true);await page.getByRole('combobox',{name:'Approver',exact:true}).click();assert.equal(await page.getByRole('option',{name:/Fixture 16/}).count(),0,'Allocator cannot also be selected as approver');await page.getByRole('heading',{name:'Property Routing',exact:true}).click();assert.equal(await page.getByRole('textbox',{name:'Search approver'}).count(),0);await page.getByRole('combobox',{name:'Allocator',exact:true}).click();assert.equal(await page.getByRole('option',{name:/Fixture 13/}).count(),1,'Changing allocator must allow swapping the two routing roles');await page.keyboard.press('Escape');await chooseRouting(page,'Allocator','Fixture 13');assert.equal(await page.getByRole('button',{name:'Save routing',exact:true}).isDisabled(),true);await chooseRouting(page,'Approver','Fixture 16');await chooseRouting(page,'Allocator','Fixture 16');await chooseRouting(page,'Approver','Fixture 13');assert.equal(await page.getByText(/backups/i).count(),0);
  await page.getByRole('button',{name:'Save routing',exact:true}).click();await page.getByText(/Routing saved/).waitFor();
  const rows=(await db.query('select user_id,is_primary from petty_cash_property_assignments where property_id=$1 and is_active',[id(3)])).rows;
  assert.equal(rows.length,2);assert.ok(rows.every(r=>r.is_primary));assert.ok(rows.some(r=>r.user_id===id(16)));
 } finally {await browser.close();await new Promise(r=>server.close(r));await db.close();}
});
for(const width of [1440,390])test(`real petty-cash UI + isolated PostgreSQL lifecycle at ${width}px`,{timeout:90000},async()=>{
 const db=await setup();const {server,url}=await fixture(db);const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 try{
  const actor=async n=>{await page.goto(`${url}/?actor=${n}`);await page.getByRole('heading',{name:'Petty Cash',exact:true}).waitFor();};
  await actor(10);await page.getByRole('button',{name:'Property Routing',exact:true}).click();await chooseRouting(page,'Allocator','Fixture 12');await chooseRouting(page,'Approver','Fixture 13');await page.getByRole('button',{name:'Save routing'}).click();await page.getByText(/Routing saved/).waitFor();await page.screenshot({path:join(scratch,`routing-${width}.png`),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));assert.ok(await page.getByRole('navigation',{name:'Petty cash views'}).getByRole('button').evaluateAll(buttons=>buttons.every(button=>button.scrollWidth<=button.clientWidth)), 'Tab labels must fit inside their buttons');await page.getByRole('combobox',{name:'Allocator',exact:true}).click();await page.getByRole('textbox',{name:'Search allocator',exact:true}).fill('Fixture');await page.screenshot({path:join(scratch,`routing-search-${width}.png`),fullPage:true});await page.keyboard.press('Escape');
  await actor(11);await page.getByRole('button',{name:'Refresh',exact:true}).waitFor({state:'visible'});await page.screenshot({path:join(scratch,`wallet-${width}.png`),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.getByRole('button',{name:'Request Petty Cash',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.waitFor();assert.equal(await dialog.getByLabel('Property',{exact:true}).count(),0);assert.equal(await dialog.locator('select').count(),2);await dialog.getByLabel('Amount (₹)',{exact:true}).fill('100');await dialog.getByLabel('Purpose',{exact:true}).fill('Fixture travel cash');await dialog.getByRole('button',{name:'Submit request'}).click();await dialog.waitFor({state:'detached'});assert.equal(await page.getByRole('button',{name:'Request Petty Cash',exact:true}).isDisabled(),true);
  await call(db,'pc_create_request',[id(16),id(1),{amount_requested:50,purpose:'Second fixture cash'}]);
  await actor(12);await page.getByRole('button',{name:'To Allocate',exact:true}).click();await page.getByLabel('Select all visible requests').check();await page.getByRole('button',{name:'Process selected (2)'}).click();await page.getByText(/2 succeeded/).waitFor();
  await actor(13);await page.getByRole('button',{name:'To Approve',exact:true}).click();await page.getByLabel('Select all visible requests').check();await page.getByRole('button',{name:'Process selected (2)'}).click();await page.getByText(/2 succeeded/).waitFor();
  await actor(14);await page.getByRole('button',{name:'To Pay',exact:true}).click();await page.getByRole('row').filter({hasText:'Fixture 11'}).getByRole('button',{name:'View'}).click();await page.getByRole('button',{name:'Mark Paid',exact:true}).click();await page.getByRole('dialog').locator('input[type=file]').setInputFiles({name:'fixture-payment.png',mimeType:'image/png',buffer:png});await page.getByText('Attached: fixture-payment.png').waitFor();await page.getByRole('button',{name:'Confirm',exact:true}).click();await page.getByRole('button',{name:'Mark Paid',exact:true}).waitFor({state:'detached'});await page.getByRole('button',{name:'Close dialog'}).click();
  await actor(11);await page.getByRole('button',{name:'View',exact:true}).first().click();await page.getByRole('button',{name:'Record expense',exact:true}).click();await page.getByRole('dialog').getByLabel('Amount (₹)',{exact:true}).fill('100');await page.getByLabel('Vendor / payee').fill('Fixture taxi');await page.getByLabel('Description / purpose').fill('Fixture travel with receipt');await page.getByRole('dialog').locator('input[type=file]').setInputFiles({name:'fixture-receipt.png',mimeType:'image/png',buffer:png});await page.getByText('Attached: fixture-receipt.png').waitFor();await page.getByRole('button',{name:'Save expense',exact:true}).click();await page.getByRole('button',{name:'Save expense',exact:true}).waitFor({state:'detached'});await page.getByText('fixture-receipt.png',{exact:true}).waitFor();
  const placement=await page.getByRole('dialog').evaluate(el=>{const overlay=el.parentElement;document.querySelector('aside').style.display='block';return {body:overlay.parentElement===document.body,aboveSidebar:overlay.contains(document.elementFromPoint(20,500))};});assert.equal(placement.body,true);assert.equal(placement.aboveSidebar,true);
  await page.screenshot({path:join(scratch,`expense-${width}.png`),fullPage:true});await page.locator('aside').evaluate(el=>el.style.removeProperty('display'));await page.getByRole('button',{name:'Close dialog'}).click();assert.equal(await page.getByRole('button',{name:'Request Petty Cash',exact:true}).isEnabled(),true);await page.getByRole('button',{name:'My Expenses',exact:true}).click();await page.getByText('Fixture travel with receipt',{exact:false}).waitFor();
  await actor(15);await page.getByRole('alert').waitFor();assert.equal(await page.getByRole('link',{name:'Petty Cash',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Request Petty Cash',exact:true}).isDisabled(),true);
  assert.deepEqual(errors,[]);const wallet=await call(db,'pc_wallet',[id(11),id(1)]);assert.equal(Number(wallet.balance),0);assert.equal(wallet.can_request,true);assert.equal((await db.query('select count(*) n from petty_cash_requests')).rows[0].n,2);console.log(`Screenshots: ${scratch}`);
 }catch(e){console.log('Browser failure artifacts:',scratch,await page.locator('body').innerText());await page.screenshot({path:join(scratch,`failure-${width}.png`),fullPage:true});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));await db.close();}
});

test('draft editing, searchable property routing and explicit primary reassignment in the real UI', { timeout: 90000 }, async () => {
 const db=await setup();const {server,url}=await fixture(db);const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',error=>errors.push(error.message));
 try {
  const actor=async n=>{await page.goto(`${url}/?actor=${n}`);await page.getByRole('heading',{name:'Petty Cash',exact:true}).waitFor();};
  await actor(11);await page.getByRole('button',{name:'Prepare draft',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Amount (₹)',{exact:true}).fill('120');await dialog.getByLabel('Purpose',{exact:true}).fill('Draft for travel');await dialog.getByRole('button',{name:'Save draft',exact:true}).click();await dialog.waitFor({state:'detached'});
  assert.equal(await page.getByRole('button',{name:'Request Petty Cash',exact:true}).isEnabled(),true);
  await page.getByRole('button',{name:'View',exact:true}).click();await page.getByRole('button',{name:'Edit or submit draft',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Amount (₹)',{exact:true}).fill('90');await dialog.getByRole('button',{name:'Save draft',exact:true}).click();await dialog.getByRole('button',{name:'Save draft',exact:true}).waitFor({state:'detached'});await page.getByRole('button',{name:'Close dialog'}).click();
  let r=(await db.query('select * from petty_cash_requests')).rows[0];assert.equal(r.status,'draft');assert.equal(Number(r.amount_requested),90);
  await db.query('insert into property_memberships(user_id,organization_id,property_id,role) values ($1,$2,$3,$4)',[id(11),id(1),id(4),'mst']);
  await db.query('insert into organization_memberships(user_id,organization_id,role) values ($1,$2,$3),($4,$2,$3),($5,$2,$3)',[id(12),id(1),'staff',id(13),id(16)]);
  await actor(10);await page.getByRole('button',{name:'Property Routing',exact:true}).click();await chooseRouting(page,'Property','Property B');await chooseRouting(page,'Allocator','Fixture 16');await chooseRouting(page,'Approver','Fixture 13');await page.getByRole('button',{name:'Save routing',exact:true}).click();await page.getByText(/Routing saved/).waitFor();
  await actor(11);await page.getByRole('button',{name:'View',exact:true}).click();await page.getByRole('button',{name:'Edit or submit draft',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Property',{exact:true}).selectOption(id(4));await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await dialog.getByRole('button',{name:'Confirm',exact:true}).waitFor({state:'detached'});await page.getByRole('button',{name:'Close dialog'}).click();
  r=(await db.query('select * from petty_cash_requests')).rows[0];assert.equal(r.property_id,id(4));assert.equal(r.assigned_allocator_id,id(16));assert.equal(r.status,'submitted');assert.equal(await call(db,'pc_can_read',[id(12),r.id]),false);
  await actor(10);await page.getByRole('button',{name:'Property Routing',exact:true}).click();await chooseRouting(page,'Property','Property B');await chooseRouting(page,'Allocator','Fixture 12');await page.getByRole('button',{name:'Save routing',exact:true}).click();await page.getByText(/Routing saved/).waitFor();assert.equal((await db.query('select assigned_allocator_id from petty_cash_requests')).rows[0].assigned_allocator_id,id(16));await page.getByRole('button',{name:'All Requests',exact:true}).click();await page.getByRole('button',{name:'View',exact:true}).click();await page.getByRole('button',{name:'Reassign routing',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Assigned allocator',{exact:true}).selectOption(id(12));await dialog.getByLabel('Assigned approver',{exact:true}).selectOption(id(13));await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await dialog.getByRole('button',{name:'Confirm',exact:true}).waitFor({state:'detached'});await page.getByRole('button',{name:'Close dialog'}).click();
  r=(await db.query('select * from petty_cash_requests')).rows[0];assert.equal(r.assigned_allocator_id,id(12));assert.equal(await call(db,'pc_can_read',[id(16),r.id]),false);
  await actor(12);await page.getByRole('button',{name:'To Allocate',exact:true}).click();await page.getByRole('button',{name:'View',exact:true}).click();await page.getByRole('button',{name:'Allocate cash',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Amount (₹)',{exact:true}).fill('80');await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await dialog.getByRole('button',{name:'Confirm',exact:true}).waitFor({state:'detached'});await page.screenshot({path:join(scratch,'draft-primary-reassignment.png'),fullPage:true});
  assert.deepEqual(errors,[]);r=(await db.query('select * from petty_cash_requests')).rows[0];assert.equal(r.status,'pending_approval');assert.equal(Number(r.allocated_amount),80);
  await db.query('update organization_memberships set is_active=false where user_id=$1',[id(12)]);
  await actor(10);await page.getByRole('button',{name:'Property Routing',exact:true}).click();await chooseRouting(page,'Property','Property B');await page.getByText(/configured user is no longer eligible/).waitFor();assert.equal(await page.getByRole('button',{name:'Save routing',exact:true}).isDisabled(),true);await chooseRouting(page,'Allocator','Fixture 16');await page.getByRole('button',{name:'Save routing',exact:true}).click();await page.getByText(/Routing saved/).waitFor();
  assert.equal((await db.query("select is_active from petty_cash_property_assignments where property_id=$1 and kind='allocator' and user_id=$2",[id(4),id(12)])).rows[0].is_active,false);
 } finally {await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();}
});

test('an expense can be saved without a bill and its remaining cash stays visible', {timeout:90000}, async()=>{
 const db=await setup();let r=await call(db,'pc_create_request',[id(11),id(1),{amount_requested:150,purpose:'Optional expense bills fixture'}]);r=await call(db,'pc_action',[id(12),r.id,'allocate',{expected_version:r.version,allocated_amount:150}]);r=await call(db,'pc_action',[id(13),r.id,'approve',{expected_version:r.version}]);
 await db.query('insert into petty_cash_uploads(id,organization_id,uploaded_by,storage_path,file_name,file_type) values ($1,$2,$3,$4,$5,$6)',[id(614),id(1),id(14),'payment.pdf','payment.pdf','application/pdf']);r=await call(db,'pc_action',[id(14),r.id,'pay',{expected_version:r.version,paid_mode:'Cash',documents:[{upload_id:id(614)}]}]);
 const {server,url}=await fixture(db);const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage();
 try{
  await page.goto(`${url}/?actor=11`);await page.getByRole('button',{name:'View',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Record expense',exact:true}).click();
  await dialog.getByLabel('Amount (₹)',{exact:true}).fill('100');await dialog.getByLabel('Vendor / payee').fill('Taxi without receipt');await dialog.getByLabel('Description / purpose').fill('Travel without a bill');assert.equal(await dialog.getByRole('button',{name:'Save expense',exact:true}).isEnabled(),true);
  await dialog.getByText(/Bills \/ receipts \(optional\)/).waitFor();await dialog.getByRole('button',{name:'Save expense',exact:true}).click();await dialog.getByRole('button',{name:'Save expense',exact:true}).waitFor({state:'detached'});await dialog.getByRole('table',{name:'Expense history'}).getByText('No bill attached',{exact:true}).waitFor();
  const wallet=await call(db,'pc_wallet',[id(11),id(1)]);assert.equal(Number(wallet.spent),100);assert.equal(Number(wallet.balance),50);assert.equal(await dialog.getByRole('button',{name:'Record expense',exact:true}).isEnabled(),true);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();}
});

test('missing payment credit blocks spending and reconciliation while historical amounts stay visible', {timeout:90000}, async()=>{
 const db=await setup();const r=await call(db,'pc_create_request',[id(11),id(1),{amount_requested:150,purpose:'Payment without credit fixture'}]);
 await db.query("update petty_cash_requests set status='paid',allocated_amount=150,approved_amount=150,paid_amount=150 where id=$1",[r.id]);
 const {server,url}=await fixture(db);const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage();
 try{
  await page.goto(`${url}/?actor=11`);await page.getByRole('button',{name:'View',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByText(/wallet credit is missing/).waitFor();assert.equal(await dialog.getByRole('button',{name:'Record expense',exact:true}).isDisabled(),true);assert.equal(await dialog.getByRole('button',{name:'Submit reconciliation',exact:true}).count(),0);
  await db.query('update petty_cash_requests set workflow_version=1 where id=$1',[r.id]);await page.reload();await page.getByRole('button',{name:'View',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByText(/Historical request/).waitFor();assert.equal(await dialog.getByText('Paid: ₹150',{exact:true}).count(),1);assert.equal(await dialog.getByText('Remaining: ₹0',{exact:true}).count(),1);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();}
});

for(const width of [1440,390])test(`partial spending keeps remaining cash with dated bill tables at ${width}px`,{timeout:90000},async()=>{
 const db=await setup();let r=await call(db,'pc_create_request',[id(11),id(1),{amount_requested:150,purpose:'Partial spend fixture'}]);
 r=await call(db,'pc_action',[id(12),r.id,'allocate',{expected_version:r.version,allocated_amount:150}]);r=await call(db,'pc_action',[id(13),r.id,'approve',{expected_version:r.version}]);
 await db.query('insert into petty_cash_uploads(id,organization_id,uploaded_by,storage_path,file_name,file_type) values ($1,$2,$3,$4,$5,$6)',[id(414),id(1),id(14),'fixture-payment.pdf','fixture-payment.pdf','application/pdf']);
 r=await call(db,'pc_action',[id(14),r.id,'pay',{expected_version:r.version,paid_mode:'Cash',documents:[{upload_id:id(414)}]}]);
 const {server,url}=await fixture(db);const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width,height:1000}});const errors=[];page.on('pageerror',error=>errors.push(error.message));
 try{
  await page.goto(`${url}/?actor=11`);await page.getByRole('button',{name:'View',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Record expense',exact:true}).click();
  await dialog.getByLabel('Amount (₹)',{exact:true}).fill('100');
  assert.equal(await dialog.getByText('Remaining after this expense: ₹50',{exact:true}).count(),1,'Partial expense must show the cash retained');
  await dialog.getByLabel('Date',{exact:true}).fill('2026-10-03');await dialog.getByLabel('Vendor / payee').fill('Taxi vendor');await dialog.getByLabel('Description / purpose').fill('First partial travel spend');await dialog.locator('input[type=file]').setInputFiles({name:'first-bill.png',mimeType:'image/png',buffer:png});await dialog.getByText('Attached: first-bill.png').waitFor();await dialog.getByRole('button',{name:'Save expense',exact:true}).click();await dialog.getByRole('button',{name:'Save expense',exact:true}).waitFor({state:'detached'});
  let wallet=await call(db,'pc_wallet',[id(11),id(1)]);assert.equal(Number(wallet.received),150);assert.equal(Number(wallet.spent),100);assert.equal(Number(wallet.balance),50);
  assert.equal(await page.getByRole('button',{name:'Request Petty Cash',exact:true}).isDisabled(),true);
  let table=dialog.getByRole('table',{name:'Expense history',exact:true});await table.getByRole('cell',{name:'03 Oct 2026',exact:true}).waitFor();await table.getByRole('link',{name:'first-bill.png',exact:true}).waitFor();await dialog.getByRole('button',{name:'Record expense',exact:true}).waitFor();
  await page.screenshot({path:join(scratch,`partial-request-${width}.png`),fullPage:true});
  await dialog.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'My Expenses',exact:true}).click();table=page.getByRole('table',{name:'Expense history',exact:true});const row=table.getByRole('row').filter({hasText:'First partial travel spend'});await row.getByRole('cell',{name:'03 Oct 2026',exact:true}).waitFor();assert.ok((await row.innerText()).includes('Property A'));assert.ok((await row.innerText()).includes(r.request_no));await row.getByRole('link',{name:'first-bill.png',exact:true}).waitFor();await page.screenshot({path:join(scratch,`partial-history-${width}.png`),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await row.getByRole('button',{name:`View ${r.request_no} and proofs`,exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Record expense',exact:true}).click();assert.equal(Number(await dialog.getByLabel('Amount (₹)',{exact:true}).getAttribute('max')),50);await dialog.getByLabel('Amount (₹)',{exact:true}).fill('50');await dialog.getByLabel('Date',{exact:true}).fill('2026-10-04');await dialog.getByLabel('Vendor / payee').fill('Second vendor');await dialog.getByLabel('Description / purpose').fill('Second partial spend');await dialog.locator('input[type=file]').setInputFiles({name:'second-bill.png',mimeType:'image/png',buffer:png});await dialog.getByText('Attached: second-bill.png').waitFor();await dialog.getByRole('button',{name:'Save expense',exact:true}).click();await dialog.getByRole('button',{name:'Save expense',exact:true}).waitFor({state:'detached'});
  await dialog.getByRole('table',{name:'Expense history'}).getByRole('cell',{name:'04 Oct 2026',exact:true}).waitFor();const dates=await dialog.getByRole('table',{name:'Expense history'}).locator('tbody time').allTextContents();assert.deepEqual(dates,['04 Oct 2026','03 Oct 2026']);wallet=await call(db,'pc_wallet',[id(11),id(1)]);assert.equal(Number(wallet.spent),150);assert.equal(Number(wallet.balance),0);assert.equal((await db.query('select count(*) n from petty_cash_expenses where request_id=$1',[r.id])).rows[0].n,2);assert.equal((await db.query("select count(*) n from petty_cash_wallet_entries where request_id=$1 and kind='credit'",[r.id])).rows[0].n,1);assert.deepEqual(errors,[]);
  console.log(`Partial spend screenshots: ${scratch}`);
 } catch(error){console.log('Partial spend failure artifacts:',scratch,await page.locator('body').innerText());await page.screenshot({path:join(scratch,`partial-failure-${width}.png`),fullPage:true});throw error;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();}
});

test('notification links open the authorized request and closing preserves unrelated query parameters',{timeout:45000},async()=>{
 const db=await setup();const request=await call(db,'pc_create_request',[id(11),id(1),{amount_requested:150,purpose:'Linked cash'}]);const {server,url}=await fixture(db);const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage();
 try{
  await page.goto(`${url}/?actor=12&request_id=${request.id}`);await page.getByRole('dialog').waitFor();await page.getByRole('dialog').getByText(request.request_no,{exact:false}).first().waitFor();await page.getByRole('button',{name:'Close dialog'}).click();assert.equal(new URL(page.url()).searchParams.get('request_id'),null);assert.equal(new URL(page.url()).searchParams.get('actor'),'12');await page.reload();assert.equal(await page.getByRole('dialog').count(),0);
  await page.goto(`${url}/?actor=11&request_id=invalid`);await page.getByRole('alert').filter({hasText:'Invalid petty cash request link'}).waitFor();assert.equal(await page.getByRole('dialog').count(),0);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();}
});
