import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { id, setup, call, create, action, paid, evidence } from './database.mjs';

test('expenses allow omitted or empty bill lists, debit once, and permit replenishment and finance review',async()=>{
 const db=await setup();try{
  let r=await paid(db);const common={description:'Travel without receipt',category:'Travel',vendor:'Taxi',expense_date:'2026-10-03',payment_mode:'Cash'};
  const first={...common,amount:60,idempotency_key:id(601)};const e=await call(db,'pc_expense',[id(11),r.id,first]);
  const migration=await readFile(new URL('../../supabase/migrations/20261005000002_petty_cash_optional_expense_bills.sql',import.meta.url),'utf8');await db.exec(migration);await db.exec(migration);
  assert.equal((await call(db,'pc_expense',[id(11),r.id,first])).id,e.id);assert.equal(Number((await call(db,'pc_wallet',[id(11),id(1)])).balance),40);
  await assert.rejects(create(db),/balance/i);
  const second=await call(db,'pc_expense',[id(11),r.id,{...common,amount:40,documents:[],idempotency_key:id(602)}]);
  assert.equal((await db.query('select count(*) n from petty_cash_documents where expense_id is not null')).rows[0].n,0);
  assert.equal((await db.query("select count(*) n from petty_cash_wallet_entries where kind='debit'")).rows[0].n,2);
  const wallet=await call(db,'pc_wallet',[id(11),id(1)]);assert.equal(Number(wallet.spent),100);assert.equal(Number(wallet.balance),0);assert.equal(wallet.can_request,true);assert.equal((await create(db)).status,'submitted');
  await call(db,'pc_review_expense',[id(14),e.id,'accepted','Reviewed expense without bill']);await call(db,'pc_review_expense',[id(14),second.id,'accepted','Reviewed expense without bill']);
  r=(await db.query('select * from petty_cash_requests where id=$1',[r.id])).rows[0];r=await action(db,11,r,'settle');r=await action(db,14,r,'close');assert.equal(r.status,'closed');
 }finally{await db.close();}
});
test('automatic property routing, assignments and no requester-selected actors',async()=>{const db=await setup();try{const r=await create(db);assert.equal(r.property_id,id(3));assert.equal(r.assigned_allocator_id,id(12));assert.equal(r.assigned_approver_id,id(13));assert.equal(r.status,'submitted');await assert.rejects(create(db,{assigned_allocator_id:id(16)}),/system configured/i);await assert.rejects(create(db),/pending request/i);await assert.rejects(call(db,'pc_create_request',[id(15),id(1),{property_id:id(3),amount_requested:100,purpose:'Vendor'}]),/Forbidden/i);}finally{await db.close();}});
test('stage guards, exact assignments, no self approval, amount limits and stale writes',async()=>{const db=await setup();try{let r=await create(db);await assert.rejects(action(db,13,r,'approve'),/stage|Forbidden/i);await assert.rejects(action(db,10,r,'allocate',{allocated_amount:100}),/Forbidden/i);await assert.rejects(action(db,12,r,'allocate',{allocated_amount:101}),/amount/i);r=await action(db,12,r,'allocate',{allocated_amount:80});assert.equal(r.status,'pending_approval');await assert.rejects(action(db,16,r,'approve'),/Forbidden/i);const old=r;r=await action(db,13,r,'approve');assert.equal(Number(r.approved_amount),80);await assert.rejects(action(db,13,old,'approve'),/changed|stage/i);await assert.rejects(action(db,14,r,'pay',{paid_amount:90}),/amount/i);}finally{await db.close();}});
test('payment credits once; supplied spend evidence stays private; zero balance permits next request before finance closure',async()=>{const db=await setup();try{const r=await paid(db);assert.equal(Number((await call(db,'pc_wallet',[id(11),id(1)])).balance),100);await assert.rejects(action(db,14,r,'pay'),/stage/i);await assert.rejects(action(db,11,r,'cancel'),/funded|stage/i);await assert.rejects(create(db),/balance/i);const upload=await evidence(db);const body={amount:100,description:'Fixture travel',category:'Travel',vendor:'Fixture',expense_date:'2026-10-03',payment_mode:'Cash',documents:[{upload_id:upload}],idempotency_key:id(80)};const e=await call(db,'pc_expense',[id(11),r.id,body]);assert.equal((await call(db,'pc_expense',[id(11),r.id,body])).id,e.id);assert.equal(Number((await call(db,'pc_wallet',[id(11),id(1)])).balance),0);const next=await create(db);assert.equal(next.status,'submitted');assert.equal((await db.query('select count(*) as n from petty_cash_wallet_entries where request_id=$1 and kind=$2',[r.id,'credit'])).rows[0].n,1);}finally{await db.close();}});
test('record visibility is owner/exact assigned actors/scoped accounts/admin, never coworker or vendor',async()=>{const db=await setup();try{const r=await create(db);for(const n of [10,11,12,13])assert.equal(await call(db,'pc_can_read',[id(n),r.id]),true);for(const n of [15,16,14])assert.equal(await call(db,'pc_can_read',[id(n),r.id]),false);let p=await action(db,12,r,'allocate',{allocated_amount:100});p=await action(db,13,p,'approve');assert.equal(await call(db,'pc_can_read',[id(14),p.id]),true);await assert.rejects(call(db,'pc_configure',[id(13),id(3),id(12),id(13)]),/Forbidden/i);await assert.rejects(call(db,'pc_configure',[id(10),id(3),id(15),id(13)]),/eligible/i);}finally{await db.close();}});
test('rejected proof blocks replenishment without refunding spent cash; receipt correction does not debit twice',async()=>{const db=await setup();try{const r=await paid(db);const upload=await evidence(db);const e=await call(db,'pc_expense',[id(11),r.id,{amount:100,description:'Fixture',vendor:'Fixture',category:'Travel',expense_date:'2026-10-03',payment_mode:'Cash',documents:[{upload_id:upload}],idempotency_key:id(80)}]);await call(db,'pc_review_expense',[id(14),e.id,'rejected','Unreadable receipt']);assert.equal(Number((await call(db,'pc_wallet',[id(11),id(1)])).balance),0);await assert.rejects(create(db),/proof/i);await db.query('insert into petty_cash_uploads(id,organization_id,uploaded_by,storage_path,file_name,file_type) values ($1,$2,$3,$4,$5,$6)',[id(120),id(1),id(11),`${id(1)}/${id(11)}/${id(120)}.pdf`,'clear.pdf','application/pdf']);await call(db,'pc_correct_expense',[id(11),e.id,{documents:[{upload_id:id(120)}],remark:'Clear receipt'}]);assert.equal(Number((await call(db,'pc_wallet',[id(11),id(1)])).balance),0);assert.equal((await create(db)).status,'submitted');}finally{await db.close();}});
test('request/expense races, precision, borrowed evidence, inactive actors, report totals and browser RLS',async()=>{const db=await setup();try{
 const outcomes=await Promise.allSettled([create(db),create(db)]);assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);
 let r=outcomes.find(r=>r.status==='fulfilled').value;
 await db.query('update property_memberships set is_active=false where user_id=$1',[id(12)]);
 await assert.rejects(action(db,12,r,'allocate',{allocated_amount:100}),/Forbidden/);
 await db.query('update property_memberships set is_active=true where user_id=$1',[id(12)]);
 r=await action(db,12,r,'allocate',{allocated_amount:100});r=await action(db,13,r,'approve');const proof=await evidence(db,14);r=await action(db,14,r,'pay',{paid_mode:'Cash',documents:[{upload_id:proof}]});
 const borrowed=await evidence(db,12);const common={description:'Fixture',category:'Travel',vendor:'Fixture',expense_date:'2026-10-03',payment_mode:'Cash'};
 await assert.rejects(call(db,'pc_expense',[id(11),r.id,{...common,amount:1.001,documents:[{upload_id:borrowed}],idempotency_key:id(201)}]),/amount/);
 await assert.rejects(call(db,'pc_expense',[id(11),r.id,{...common,amount:1,documents:[{upload_id:borrowed}],idempotency_key:id(202)}]),/owned/);
 const upload=await evidence(db);const spends=await Promise.allSettled([call(db,'pc_expense',[id(11),r.id,{...common,amount:70,documents:[{upload_id:upload}],idempotency_key:id(203)}]),call(db,'pc_expense',[id(11),r.id,{...common,amount:70,documents:[{upload_id:upload}],idempotency_key:id(204)}])]);assert.equal(spends.filter(x=>x.status==='fulfilled').length,1);assert.equal(Number((await call(db,'pc_wallet',[id(11),id(1)])).balance),30);
 const report=await call(db,'pc_report',[id(10),id(1)]);assert.equal(Number(report.totals.paid),100);assert.equal(Number(report.totals.spent),70);assert.equal((await call(db,'pc_report',[id(16),id(1)])).rows.length,0);
 await db.exec(`INSERT INTO storage.objects(bucket_id,name) VALUES ('petty_cash_evidence','fixture'),('unrelated-module','keep');GRANT USAGE ON SCHEMA storage TO authenticated;GRANT SELECT ON storage.objects TO authenticated;CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT current_setting('test.actor',true)::uuid $$;GRANT USAGE ON SCHEMA auth TO authenticated;GRANT SELECT ON petty_cash_requests,petty_cash_documents,petty_cash_expenses,petty_cash_wallet_entries TO authenticated;SET ROLE authenticated;`);
 await db.query("select set_config('test.actor',$1,false)",[id(16)]);assert.equal((await db.query('select * from petty_cash_requests')).rows.length,0);assert.equal((await db.query('select * from petty_cash_documents')).rows.length,0);
 await db.query("select set_config('test.actor',$1,false)",[id(11)]);assert.equal((await db.query('select * from petty_cash_requests')).rows.length,1);assert.equal((await db.query('select * from petty_cash_expenses')).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows[0].bucket_id,'unrelated-module');await assert.rejects(db.query("select pc_create_request($1,$2,$3)",[id(11),id(1),{}]),/permission denied/);
 }finally{await db.close();}});
test('multiple properties require selection, cross-org property denied and funded/closed data is retained',async()=>{const db=await setup();try{
 await db.query('insert into property_memberships(user_id,organization_id,property_id,role) values ($1,$2,$3,$4)',[id(11),id(1),id(4),'mst']);await assert.rejects(create(db),/Select an assigned property/);await assert.rejects(create(db,{property_id:id(999)}),/Forbidden property/);
 let r=await create(db,{property_id:id(3)});r=await action(db,12,r,'allocate',{allocated_amount:100});r=await action(db,13,r,'approve');const proof=await evidence(db,14);r=await action(db,14,r,'pay',{paid_mode:'Cash',documents:[{upload_id:proof}]});
 r=await action(db,14,r,'return',{amount_returned:100,remark:'Confirmed fixture return'});r=await action(db,11,r,'settle');r=await action(db,14,r,'close');assert.equal(r.status,'closed');assert.equal(Number((await call(db,'pc_wallet',[id(11),id(1)])).balance),0);assert.equal((await db.query('select count(*) n from petty_cash_requests')).rows[0].n,1);
 }finally{await db.close();}});
test('legacy advances retain balances and bills, accept new settlement proofs without replaying payment',async()=>{const db=await setup();try{
 const r=(await db.query("insert into petty_cash_requests(organization_id,property_id,requester_id,amount_requested,purpose,status,paid_amount,paid_at) values ($1,$2,$3,100,'Historical advance','paid',100,now()) returning *",[id(1),id(3),id(11)])).rows[0];
 await assert.rejects(create(db),/existing advance/);const upload=await evidence(db);
 let updated=await action(db,11,r,'settle',{actual_spent:100,documents:[{upload_id:upload,amount:100,bill_date:'2026-10-03',vendor:'Historical vendor'}]});
 const doc=(await db.query('select * from petty_cash_documents where request_id=$1',[r.id])).rows[0];assert.ok(doc);assert.equal(Number(doc.amount),100);
 await call(db,'pc_review_bill',[id(14),doc.id,'accepted','Verified historical receipt']);updated=(await db.query('select * from petty_cash_requests where id=$1',[r.id])).rows[0];updated=await action(db,14,updated,'close');assert.equal(updated.status,'closed');assert.equal((await db.query('select * from petty_cash_wallet_entries')).rows.length,0);assert.equal((await create(db)).status,'submitted');
 }finally{await db.close();}});
test('explicit reassignment restarts allocation and retains the earlier action in audit history',async()=>{const db=await setup();try{
 let r=await create(db);r=await action(db,12,r,'allocate',{allocated_amount:80,remark:'Earlier allocation'});
 await call(db,'pc_configure',[id(10),id(3),id(16),id(13)]);
 r=await action(db,10,r,'reassign');assert.equal(r.status,'submitted');assert.equal(r.assigned_allocator_id,id(16));assert.equal(r.allocated_amount,null);assert.equal(r.allocated_by,null);assert.equal(r.allocated_at,null);assert.equal(r.allocation_remarks,null);
 assert.equal((await db.query("select count(*) n from petty_cash_activity where request_id=$1 and action='allocate'",[r.id])).rows[0].n,1);
 await assert.rejects(action(db,12,r,'allocate',{allocated_amount:80}),/Forbidden/);r=await action(db,16,r,'allocate',{allocated_amount:90});assert.equal(Number(r.allocated_amount),90);
 }finally{await db.close();}});
test('Supabase default grants cannot expose backend actor RPCs, and settlement view respects caller RLS',async()=>{const db=await setup();try{
 const r=await create(db);const acl=(await db.query("select proname,has_function_privilege('anon',oid,'EXECUTE') a,has_function_privilege('authenticated',oid,'EXECUTE') c from pg_proc where pronamespace='public'::regnamespace and proname like 'pc_%'")).rows;
 for(const f of acl){assert.equal(f.a,false,f.proname+' exposed to anon');if(!['pc_current_can_read','pc_current_super'].includes(f.proname))assert.equal(f.c,false,f.proname+' exposed to authenticated');}
 await db.exec(`CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT current_setting('test.actor',true)::uuid $$;GRANT USAGE ON SCHEMA auth TO authenticated;GRANT SELECT ON petty_cash_settlement_status,petty_cash_requests,petty_cash_documents TO authenticated;SET ROLE authenticated;`);
 await db.query("select set_config('test.actor',$1,false)",[id(16)]);assert.equal((await db.query('select * from petty_cash_settlement_status')).rows.length,0);
 await db.query("select set_config('test.actor',$1,false)",[id(11)]);assert.equal((await db.query('select * from petty_cash_settlement_status')).rows[0].request_id,r.id);
 }finally{await db.close();}});
test('legacy rejected bill can be superseded with preserved evidence and no duplicate accounted money',async()=>{const db=await setup();try{
 let r=(await db.query("insert into petty_cash_requests(organization_id,property_id,requester_id,amount_requested,purpose,status,paid_amount,paid_at) values ($1,$2,$3,100,'Historical correction','paid',100,now()) returning *",[id(1),id(3),id(11)])).rows[0];
 const upload=await evidence(db);r=await action(db,11,r,'settle',{documents:[{upload_id:upload,amount:100,bill_date:'2026-10-03',vendor:'Historical vendor'}]});const original=(await db.query('select * from petty_cash_documents where request_id=$1',[r.id])).rows[0];await call(db,'pc_review_bill',[id(14),original.id,'rejected','Unreadable']);
 const replacement=id(300);await db.query('insert into petty_cash_uploads(id,organization_id,uploaded_by,storage_path,file_name,file_type) values ($1,$2,$3,$4,$5,$6)',[replacement,id(1),id(11),`${id(1)}/${id(11)}/${replacement}.pdf`,'corrected.pdf','application/pdf']);r=(await db.query('select * from petty_cash_requests where id=$1',[r.id])).rows[0];
 r=await action(db,11,r,'settle',{documents:[{upload_id:replacement,amount:100,bill_date:'2026-10-03',vendor:'Historical vendor',replaces_document_id:original.id}]});const corrected=(await db.query('select * from petty_cash_documents where upload_id=$1',[replacement])).rows[0];await call(db,'pc_review_bill',[id(14),corrected.id,'accepted','Verified']);
 const kept=(await db.query('select * from petty_cash_documents where id=$1',[original.id])).rows[0];assert.equal(kept.review_status,'rejected');assert.equal(kept.superseded_by,corrected.id);const s=(await db.query('select * from petty_cash_settlement_status where request_id=$1',[r.id])).rows[0];assert.equal(Number(s.bills_total),100);assert.equal(Number(s.bills_rejected),0);r=(await db.query('select * from petty_cash_requests where id=$1',[r.id])).rows[0];r=await action(db,14,r,'close');assert.equal(r.status,'closed');assert.equal((await create(db)).status,'submitted');assert.equal((await db.query('select count(*) n from petty_cash_documents')).rows[0].n,2);
 }finally{await db.close();}});
