'use client';
import { useEffect,useState } from 'react';
import { PC_NOTIFICATION_EVENTS,PC_NOTIFICATION_TEMPLATES } from '@/frontend/lib/notifications/pettyCashTemplates';
function defaultEmail(key:string){const event=PC_NOTIFICATION_EVENTS.find(event=>event.key===key)!;const template=PC_NOTIFICATION_TEMPLATES.find(template=>template.name===event.templateName)!;const body=template.body.replace(/{{(\d+)}}/g,(_,n)=>`{{${template.params[Number(n)-1]}}}`);return {subject:`${event.name}: {{request_no}}`,html:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;padding:24px"><h2>${event.name}</h2><p>{{event_date}}</p><p>${body.replace(/\n/g,'<br>')}</p><p><a href="{{request_url}}">View petty cash request</a></p></div>`,design:null};}
export default function PettyCashEmailTemplates({organizationId}:{organizationId:string}){
    const [templates,setTemplates]=useState<Record<string,any>>({});const [key,setKey]=useState('petty_cash_submitted');const [loaded,setLoaded]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
    useEffect(()=>{const controller=new AbortController();setLoaded(false);setTemplates({});setMessage('');void fetch(`/api/admin/organizations/${organizationId}`,{signal:controller.signal}).then(async response=>{const settings=await response.json();if(!response.ok)throw new Error('Could not load email templates');if(!controller.signal.aborted){setTemplates(settings.email_templates||{});setLoaded(true);}}).catch(error=>{if(!controller.signal.aborted)setMessage(error.message);});return()=>controller.abort();},[organizationId]);
    const value=templates[key]||defaultEmail(key);const event=PC_NOTIFICATION_EVENTS.find(event=>event.key===key)!;const template=PC_NOTIFICATION_TEMPLATES.find(template=>template.name===event.templateName)!;
    const edit=(field:string,text:string)=>setTemplates(current=>({...current,[key]:{...value,[field]:text}}));
    return <section className="space-y-3 rounded-xl border bg-white p-4" aria-label="Petty Cash email templates"><h3 className="font-semibold">Petty Cash email templates</h3><p className="text-xs text-slate-600">Email follows the same Omnichannel recipients and channel rules. Built-in templates are available; customize an event here if needed. Saving a template does not enable sending.</p><label className="block text-xs">Email event<select className="mt-1 w-full rounded-lg border p-2" aria-label="Petty Cash email event" value={key} onChange={event=>{setKey(event.target.value);setMessage('');}}>{PC_NOTIFICATION_EVENTS.map(event=><option key={event.key} value={event.key}>{event.name}</option>)}</select></label><label className="block text-xs">Email subject<input className="mt-1 w-full rounded-lg border p-2" value={value.subject||defaultEmail(key).subject} onChange={event=>edit('subject',event.target.value)} /></label><label className="block text-xs">Email HTML<textarea className="mt-1 min-h-48 w-full rounded-lg border p-2 font-mono" value={value.html} onChange={event=>edit('html',event.target.value)} /></label><p className="break-words text-xs text-slate-600">Variables: {[...template.params,'event_date'].filter((param,i,all)=>all.indexOf(param)===i).map(param=>`{{${param}}}`).join(', ')}</p><div className="flex flex-wrap gap-2"><button type="button" className="rounded-lg border px-3 py-2 text-xs" disabled={!loaded||busy} onClick={()=>setTemplates(current=>({...current,[key]:defaultEmail(key)}))}>Use built-in email template</button><button type="button" className="rounded-lg bg-primary px-3 py-2 text-xs text-white" disabled={!loaded||busy} onClick={async()=>{setBusy(true);setMessage('');try{const response=await fetch(`/api/admin/organizations/${organizationId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({email_templates:{...templates,[key]:value}})});if(!response.ok)throw new Error('Could not save email templates');setMessage('Petty Cash email template saved.');}catch(error){setMessage(error instanceof Error?error.message:'Could not save email templates');}finally{setBusy(false);}}}>Save Petty Cash email template</button></div>{message&&<p role="status" className="text-xs">{message}</p>}</section>;
}
